run:
  timeout: 5m

linters:
  # We run with all default linters enabled and in addition the linters
  # listed below.
  enable:
    - bodyclose
    - errorlint
    - copyloopvar
    - goimports
    - gosec
    - makezero
    - revive
    - unconvert
    - unparam
    - wastedassign

issues:
  exclude-dirs:
    - _test

linters-settings:
  goimports:
    local-prefixes: github.com/fraenky8/tables-to-go/v2

  gosec:
    config:
      G306: "0666"
