checks:
  go: true

build:
  project_setup:
    override:
      - go build -mod=vendor .
  environment:
    go: go1.13
  nodes:
    analysis:
      tests:
        override:
          - go-scrutinizer-run
          - govet-run
          - golint-run
    coverage:
      tests:
        override:
          -
            command: go test -mod=vendor -coverprofile=cover.out ./...
            coverage:
              file: 'cover.out'
              format: 'go-cc'

filter:
  excluded_paths:
    - "*/*_test.go"
  dependency_paths:
    - "vendor/"
