name: Go & Lint
on: [push]
permissions:
  contents: read
jobs:
  golangci:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Build
        run: go build -v -mod=vendor .

      - name: Test
        run: go test -v -mod=vendor -race ./...
