name: Go
on: [push]
permissions:
  contents: read
jobs:
  build:
    name: Build & Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v -mod=vendor .

      - name: Test
        run: go test -v -mod=vendor -race ./...
